[settings]
timeout = 1000

[relaychain]
chain = "local"
default_command = "./target/release/solochain-template-node"
default_keystore_key_types = ["gran", "aura", "loc!"]

[[relaychain.nodes]]
name = "alice"
rpc_port = 9944
validator = true

[[relaychain.nodes]]
name = "bob"
rpc_port = 9945
validator = true
