[settings]
timeout = 1000

[relaychain]
chain = "local"
default_command = "./target/release/solochain-template-node"

[[relaychain.nodes]]
args = ["--alice"]
name = "alice"
port = 30333
rpc_port = 9944
validator = true

[[relaychain.nodes]]
args = ["--bob"]
name = "bob"
port = 30334
rpc_port = 9945
validator = true
